# Generated by Django 3.0.6 on 2020-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gram',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
