# Generated by Django 3.0.6 on 2020-05-17 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0002_auto_20200517_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='gram',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gram',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gram',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
