# Generated by Django 3.0.6 on 2020-05-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200518_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gram',
            old_name='img',
            new_name='Photo',
        ),
    ]
